# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.2"
manifest_format = "2.0"

[[deps.ToyRockets]]
path = "ToyRockets"
uuid = "5e012411-bb1a-41c0-a378-1255cf584bd1"
version = "0.1.0"
