
CXX=../../bin/docker-compile.sh
CXXFLAGS:=-std=gnu++2a -Wall -Wextra -g -pthread -fdiagnostics-color=never

23-templates-deduct-01.x: 23-templates-deduct-01.cpp
	$(CXX) $(CXXFLAGS) 23-templates-deduct-01.cpp -o 23-templates-deduct-01.x
